// Generated by CoffeeScript 1.12.4
(function() {
  var AJV, Superagent, Supertest, Test, Util, app, swaggerSchema;

  Test = require('tape');

  Supertest = require('supertest');

  Superagent = require('superagent');

  Util = require('util');

  AJV = new (require('ajv'))({
    allErrors: true,
    verbose: true
  });

  process.env.HOST_AND_PORT = 'example.org:32';

  process.env.BASEPATH = '/';

  app = require('express')();

  app.use(require('../lib/route/swagger'));

  swaggerSchema = 'https://rawgit.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json';

  Test('Valid swagger', function(t) {
    return Supertest(app).get('/json').expect('Content-Type', /application\/json/).expect(200).end(function(err, res) {
      var json;
      t.ok(!err, "HTTP headers as expected");
      json = res.body;
      return Superagent.get(swaggerSchema).end(function(err, res) {
        var schema;
        schema = res.body;
        AJV.validate(schema, json);
        t.ok(!AJV.errors, "No validation erros");
        if (AJV.errors) {
          console.log(Util.inspect(AJV.errors, {
            colors: true,
            depth: 4
          }));
        }
        return t.end();
      });
    });
  });

}).call(this);
