version: '2'
services:
  zts-simpleapi:
    container_name: 'zts-simpleapi-app'
    build: '.'
    restart: 'always'
    ports:
      - '${ZTS_PORT}:1970'
    environment:
      HOST_AND_PORT: '${ZTS_HOST}'
      BASEPATH: '${BASEPATH}'
      ZTS_URI: 'http://zts-app:1969'
      SWAGGER_URI: 'http://zts-swagger-app:8888'
      SIMPLEAPI_CACHE_ENABLED: '${ENABLE_CACHE}'
  zts:
    container_name: 'zts-app'
    restart: 'always'
    image: '${ZTS_DOCKER_IMAGE}:${ZTS_DOCKER_TAG}'
    volumes:
      - '${PWD}/translators:/opt/zts/modules/zotero/translators'
  zts-swagger:
    image: 'sjeandeaux/docker-swagger-ui'
    restart: 'always'
    container_name: 'zts-swagger-app'
    environment:
      API_URL: 'swagger/json'
