version: '2'
services:
  zts-simpleapi:
    container_name: 'zts-simpleapi-app'
    build: '.'
    restart: 'on-failure'
    # volumes:
    #   - './src:/app/src'
    ports:
      - '1970:1970'
    depends_on:
      - 'zts'
      - 'zts-swagger'
    environment:
      HOST_AND_PORT: 'localhost:1970'
      BASEPATH: '/'
      ZTS_URI: 'http://zts-app:1969'
      SWAGGER_URI: 'http://zts-swagger-app:8888'
  zts:
    container_name: 'zts-app'
    image: 'kbai/zts:46.0'
    volumes:
      - './translators:/opt/zts/modules/zotero/translators'
  zts-swagger:
    image: 'sjeandeaux/docker-swagger-ui'
    container_name: 'zts-swagger-app'
    environment:
      API_URL: '/swagger/json'

