swagger: '2.0'
############
#   INFO   #
############
info:
  version: "0.0.0"
  title: Translation Server API
  description: |
    https://github.com/zotero/translation-server
    by zuphilip
schemes:
  - http
host: '{{{ HOST_AND_PORT }}}'
basePath: '{{{ BASEPATH }}}'
securityDefinitions: {}
consumes:
  - application/json
produces:
  - application/json
##############
#    PATHS   #
##############
paths:
  '{{{ SIMPLEAPI_BASEPATH }}}/':
    get:
      tags: ['Simple Scraper API']
      summary: Retrieve bibliographic data as JSON scraped from a URI
      description: |
        Combines the `/web` and `/export` endpoints to let the consumer define the desired output format
      parameters:
        - name: format
          in: query
          type: string
          # Not possible in Swagger 2.0, will be in 3.0
          # enum:
          #   - doi
          #   - bibtex
          #   - bookmarks
          #   - coins
          #   - mods
          #   - refer
          #   - rdf_bibliontology
          #   - rdf_dc
          #   - rdf_zotero
          #   - ris
          #   - tei
          #   - wikipedia
        - name: url
          in: query
          type: string
          pattern: uri
      responses:
        200:
          description: Formatted bibliographic record(s)
  '{{{ SIMPLEAPI_BASEPATH }}}/cache':
    get:
      tags: ['Simple Scraper API']
      summary: Get cache size
      responses:
        200:
          description: Number of cached entries
    delete:
      tags: ['Simple Scraper API']
      summary: Empty the cache
      responses:
        200:
          description: Deleted cache successfully
  '{{{ ZTS_BASEPATH }}}/refresh':
    get:
      tags: ['Zotero Translation Server API']
      summary: Refreshes the translator directory
      description: |
        <del>Refreshes the translator directory by calling git.</del> Translators are managed on the level of
        zts-in-a-box.
      responses:
        200:
          description: Success
        400:
          description: Failure, depending upon git exit status
  '{{{ ZTS_BASEPATH }}}/web':
    post:
      tags: ['Zotero Translation Server API']
      summary: Translates a web page
      parameters:
        - 
          name: webrequest
          in: body
          description: a URL to translate
          required: true
          schema:
            $ref: '#/definitions/Url'
      responses:
        200:
          description: Ok
  '{{{ ZTS_BASEPATH }}}/import':
    post:
      tags: ['Zotero Translation Server API']
      summary: Converts input in any format Zotero can import to items in Zotero server JSON format
      parameters:
        -
          name: importrequest
          in: body
          description: File to import
          required: true
          schema:
            $ref: '#/definitions/File'
      responses:
        200:
          description: Ok
  '{{{ ZTS_BASEPATH }}}/export':
    post:
      tags: ['Zotero Translation Server API']
      summary: Converts input in Zotero server JSON format to items Zotero can import
      parameters:
        -
          name: exportrequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/Export'
        - name: format
          in: query
          required: true
          type: string
          # Not possible in Swagger 2.0, will be in 3.0
          # example: ris
          # enum:
          #   - bibtex
          #   - bookmarks
          #   - coins
          #   - mods
          #   - refer
          #   - rdf_bibliontology
          #   - rdf_dc
          #   - rdf_zotero
          #   - ris
          #   - tei
          #   - wikipedia
      responses:
        200:
          description: Ok
        400:
          description: Not ok
##################
#   DEFINITIONS  #
##################
definitions:
  Url:
    type: object
    properties:
      url:
        type: string
      sessionid:
        type: string
    example: |
      {
        "url":"http://www.tandfonline.com/doi/abs/10.1080/15424060903167229",
        "sessionid":"abc123"
      }
  File:
    type: string
    example: |
      "TY  - JOUR
      TI  - Die Grundlage der allgemeinen Relativitätstheorie
      AU  - Einstein, Albert
      PY  - 1916
      SP  - 769
      EP  - 822
      JO  - Annalen der Physik
      VL  - 49
      ER  -"
  Export:
    type: array
    items:
      type: object
    example: |
      '[
        [
          {
            "itemKey":"QXJRT3QB",
            "itemVersion":0,
            "itemType":"journalArticle",
            "creators":
            [
              {
                "firstName":"Jessica",
                "lastName":"Trinoskey",
                "creatorType":"author"
              },
              {
                "firstName":"Frances A.",
                "lastName":"Brahmi",
                "creatorType":"author"
              },
              {
                "firstName":"Carole",
                "lastName":"Gall",
                "creatorType":"author"
              }
            ],
            "tags":[],
            "title":"Zotero: A Product Review",
            "publicationTitle":"Journal of Electronic Resources in Medical Libraries",
            "volume":"6",
            "issue":"3",
            "pages":"224-229",
            "date":"September 9, 2009",
            "DOI":"10.1080/15424060903167229",
            "url":"http://dx.doi.org/10.1080/15424060903167229",
            "abstractNote":"Zotero is a free and open source Firefox extension that exists within the Web browser and allows one to collect, manage, store, and cite resources in a single location. 1 Zotero automatically imports citation information from a number of sources, including nonsubscription, newspaper, and commercial Web sites, and Web-based databases such as PubMed and MedlinePlus. Zotero offers more options for note taking than the better-known citation management system EndNote. Sixteen citation styles are available when Zotero is initially downloaded, with many more freely available. Users can install a plug-in that allows Zotero to integrate with Microsoft Word. Even though Zotero does not have an on-demand customer support service, its Web site offers a wealth of information for users. The authors highly recommend Zotero.",
            "ISSN":"1542-4065",
            "libraryCatalog":"Taylor and Francis+NEJM",
            "accessDate":"CURRENT_TIMESTAMP",
            "shortTitle":"Zotero"
          }
        ]
      ]'

